# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
#image: node:latest
image: trion/ng-cli-karma

cache:
  paths:
  - node_modules/

test:
   script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng lint
    - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng e2e
